+++ title = "About" description = "A page all about me!" date = "2024-11-15" aliases = ["about-us", "about-me"] author = "Roudy" +++

Here is some info about me:
I am Lebanese-Canadian
I live in Lebanon
I like Planes
I like Cars
I like Traveling
I am born in Canada (MontrÃ©al)
I like Kanye
I like music
